AWSTemplateFormatVersion: 2010-09-09
Description: Jupyter Notebook Template

Resources:
  InstanceSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Enable SSH access via port 22
      GroupName: JupyterNotebook-SSH-SG
      VpcId: 
        Fn::ImportValue: VPCExport

  InboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt InstanceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
